[package]
name = "vrf-deck-pocker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schnorrkel = "0.11.4"
rand = "0.8"  # Check for the latest version on crates.io
